### PR TITLE
Team page improvements

### PR DESCRIPTION
**Pull request by ValeriaAhmetzhanova**

### CODE REVIEW

**Comment by JackieBinya** [comment]
@ValeriaAhmetzhanova the popup modal is positioned above the menu in all screens(as shown in the images below). 
I suggest you lower it such that its close button doesn't sit directly above the free trial button in the menu.

Alternatively I think you could maybe decrease the opacity of the overlay.

Screenshot from 2021-03-09 12-09-57
Screenshot from 2021-03-09 12-09-09

**Comment by JackieBinya** [comment]
@ValeriaAhmetzhanova, I will leave this one open until we have all the updated team members pictures...

**Comment by ValeriaAhmetzhanova** [comment]
> @ValeriaAhmetzhanova, I will leave this one open until we have all the updated team members pictures...

Maybe I can create a new branch later to put new photos to prevent merge conflicts appear? Will fix the positioning now

**Comment by ValeriaAhmetzhanova** [comment]
Seems like it depends on screen size.. At my screen it's ok

**Comment by JackieBinya** [comment]
@ValeriaAhmetzhanova merged...

**Pull request merged**
